server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /templates
      suffix: .html


logging:
  config: logback.xml
  level:
    com.chengnanhuakai.upload.mapper: trace

# 七牛云配置
qiniu:
  accessKey: 62UNf6EeRYaQ8wUdc5CWm3II4zvaxnb7tYTNEKCJ
  secretKey: T31i2JI2DytG4P-6F4g3CwN_WcVLnnODuXgYLeFn
  bucket: chengnan
